### ISSUE TITLE
No module named 'deltacnn.cuda'

### ISSUE THREAD

**Issue by CheungBH** [facebookresearch/DeltaCNN#2]
Hello. Thanks for your great work. When I was running your example, an error occurs to me: 
**No module named 'deltacnn.cuda'**
I successfully built the module using 
_python setup.py install --user_
It can find package deltacnn, but it cannot find the cuda submodule.
How could I fix it?

**Comment by dabeschte** [comment]
Hi!
That sounds like there was a problem in the installation process. Could you try reinstalling DeltaCNN and parse the output logs for errors? Most likely, it did not find a working c++ or cuda compiler. But it is difficult to tell, because I never ran into the issue myself

**Comment by CheungBH** [comment]
Hello. Thanks for your respond.
I just run a two-step installation
1. pip install torch==1.12.0+cu116 torchvision==0.13.0+cu116 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu116
2. python setup.py install --user

And the second step shows:

**(delta) baoheng@americano02:/media/hdd1t/baoheng/DeltaCNN$ python setup.py install --user
running install
/media/hdd1t/baoheng/anaconda3/envs/delta/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/media/hdd1t/baoheng/anaconda3/envs/delta/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing src/torchdeltacnn.egg-info/PKG-INFO
writing dependency_links to src/torchdeltacnn.egg-info/dependency_links.txt
writing top-level names to src/torchdeltacnn.egg-info/top_level.txt
reading manifest file 'src/torchdeltacnn.egg-info/SOURCES.txt'
adding license file 'LICENSE.txt'
writing manifest file 'src/torchdeltacnn.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/deltacnn
copying build/lib/deltacnn/__init__.py -> build/bdist.linux-x86_64/egg/deltacnn
copying build/lib/deltacnn/cuda_kernels.py -> build/bdist.linux-x86_64/egg/deltacnn
copying build/lib/deltacnn/filter_conversion.py -> build/bdist.linux-x86_64/egg/deltacnn
copying build/lib/deltacnn/logging_layers.py -> build/bdist.linux-x86_64/egg/deltacnn
copying build/lib/deltacnn/sparse_layers.py -> build/bdist.linux-x86_64/egg/deltacnn
copying build/lib/deltacnn/utils.py -> build/bdist.linux-x86_64/egg/deltacnn
byte-compiling build/bdist.linux-x86_64/egg/deltacnn/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/deltacnn/cuda_kernels.py to cuda_kernels.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/deltacnn/filter_conversion.py to filter_conversion.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/deltacnn/logging_layers.py to logging_layers.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/deltacnn/sparse_layers.py to sparse_layers.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/deltacnn/utils.py to utils.cpython-39.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/torchdeltacnn.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/torchdeltacnn.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/torchdeltacnn.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/torchdeltacnn.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/torchdeltacnn-0.0.0-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torchdeltacnn-0.0.0-py3.9.egg
Removing /home/baoheng/.local/lib/python3.9/site-packages/torchdeltacnn-0.0.0-py3.9.egg
Copying torchdeltacnn-0.0.0-py3.9.egg to /home/baoheng/.local/lib/python3.9/site-packages
torchdeltacnn 0.0.0 is already the active version in easy-install.pth

Installed /home/baoheng/.local/lib/python3.9/site-packages/torchdeltacnn-0.0.0-py3.9.egg
Processing dependencies for torchdeltacnn==0.0.0
Finished processing dependencies for torchdeltacnn==0.0.0**

Is it normal？

**Comment by dabeschte** [comment]
Ah, I see. It did not compile the cuda files. I should add an error message there. Please set the "CUDA_HOME" path variable to wherever you have cuda installed. That should fix it.

**Comment by CheungBH** [comment]
> Ah, I see. It did not compile the cuda files. I should add an error message there. Please set the "CUDA_HOME" path variable to wherever you have cuda installed. That should fix it.

Thank you for your reply. I can currently run your example now!
By the way, another problem occurs to me. Could you please provide some suggestions?
I successfully in running your demo using terminal. However, when I am going to debug your project with IDLE like pycharm or Clion, the "deltacnn.cuda" is still not found (deltacnn can be imported).

I print the "deltacnn" path after importing, and I found that it is imported from different location using terminal and IDLE:

**Using temrinal: <module 'deltacnn' from '/home/baoheng/.local/lib/python3.9/site-packages/torchdeltacnn-0.0.0-py3.9-linux-x86_64.egg/deltacnn/__init__.py'> (Successful)**
**Using IDLE: <module 'deltacnn' from '/media/sda1/baoheng/DeltaCNN/src/deltacnn/__init__.py'> (Failed)**

I am not very familiar with cuda programming. Are there anything I should do to ensure the code is debuggable with IDLE?

**Comment by CheungBH** [comment]
I fixed it. Thanks
